import { getDictionary, type Locale } from "@/lib/i18n";
import type { Game, GameTag } from "@/types/game";

export type RentalTier = "under-100" | "over-100";

export type RentalTerms = {
  tier: RentalTier;
  advancePaymentCents: number;
  rentalPricePerDayCents: number;
};

const RENTAL_TERMS: Record<RentalTier, RentalTerms> = {
  "under-100": {
    tier: "under-100",
    advancePaymentCents: 5000,
    rentalPricePerDayCents: 2000,
  },
  "over-100": {
    tier: "over-100",
    advancePaymentCents: 10000,
    rentalPricePerDayCents: 3500,
  },
};

const GAME_BASE = [
  {
    slug: "codenames",
    title: "Codenames",
    playerCount: "4–8+",
    duration: "15–30 min",
    ageMin: 10,
    tags: ["corporate", "communication", "rentable", "rent-over-100"] as GameTag[],
    featured: true,
  },
  {
    slug: "the-resistance",
    title: "The Resistance",
    playerCount: "5–10",
    duration: "30–45 min",
    ageMin: 13,
    tags: ["corporate", "social-deduction", "rentable", "rent-under-100"] as GameTag[],
    featured: true,
  },
  {
    slug: "wavelength",
    title: "Wavelength",
    playerCount: "2–12+",
    duration: "30–45 min",
    ageMin: 14,
    tags: ["corporate", "communication", "rentable", "rent-over-100"] as GameTag[],
    featured: true,
  },
  {
    slug: "decrypto",
    title: "Decrypto",
    playerCount: "3–8",
    duration: "15–45 min",
    ageMin: 12,
    tags: ["corporate", "communication", "rentable", "rent-over-100"] as GameTag[],
  },
  {
    slug: "just-one",
    title: "Just One",
    playerCount: "3–7",
    duration: "20 min",
    ageMin: 8,
    tags: ["corporate", "communication", "kids", "rentable", "rent-under-100"] as GameTag[],
  },
  {
    slug: "dixit",
    title: "Dixit",
    playerCount: "3–6",
    duration: "30 min",
    ageMin: 8,
    tags: ["kids", "rentable", "rent-over-100"] as GameTag[],
  },
  {
    slug: "forbidden-island",
    title: "Forbidden Island",
    playerCount: "2–4",
    duration: "30 min",
    ageMin: 10,
    tags: ["kids", "communication", "rentable", "rent-over-100"] as GameTag[],
  },
  {
    slug: "ticket-to-ride",
    title: "Ticket to Ride",
    playerCount: "2–5",
    duration: "30–60 min",
    ageMin: 8,
    tags: ["kids", "rentable", "rent-over-100"] as GameTag[],
  },
  {
    slug: "splendor",
    title: "Splendor",
    playerCount: "2–4",
    duration: "30 min",
    ageMin: 10,
    tags: ["rentable", "rent-over-100"] as GameTag[],
  },
  {
    slug: "azul",
    title: "Azul",
    playerCount: "2–4",
    duration: "30–45 min",
    ageMin: 8,
    tags: ["corporate", "kids", "rentable", "rent-over-100"] as GameTag[],
    featured: true,
  },
  {
    slug: "carcassonne",
    title: "Carcassonne",
    playerCount: "2–5",
    duration: "30–45 min",
    ageMin: 7,
    tags: ["kids", "rentable", "rent-over-100"] as GameTag[],
  },
  {
    slug: "collectives9",
    title: "Collectives 9",
    playerCount: "2–16",
    duration: "40–90 min",
    ageMin: 12,
    tags: ["corporate", "kids", "rentable", "rent-over-100"] as GameTag[],
  },
  {
    slug: "flip7",
    title: "Flip7",
    playerCount: "3–18",
    duration: "20 min",
    ageMin: 8,
    tags: ["corporate", "kids","party-games","card-game", "rentable", "rent-under-100"] as GameTag[],
  },
  {
    slug: "port-royal",
    title: "Port Royal",
    playerCount: "2–5",
    duration: "20-50 min",
    ageMin: 8,
    tags: ["corporate","card-game", "rentable", "rent-under-100"] as GameTag[],
  },
  {
    slug: "the-mind",
    title: "The Mind",
    playerCount: "2-4",
    duration: "20 min",
    ageMin: 8,
    tags: ["corporate","logic-games","card-game","kids","party-games","communication", "rentable", "rent-under-100"] as GameTag[],
  },
  {
    slug: "love-letter",
    title: "Love Letter",
    playerCount: "2-6",
    duration: "20 min",
    ageMin: 10,
    tags: ["corporate", "party-games", "card-game", "rentable", "rent-under-100"] as GameTag[],
  },
  {
    slug: "sheriff-of-nottingham",
    title: "Sheriff of Nottingham",
    playerCount: "3-5",
    duration: "30 min",
    ageMin: 10,
    tags: ["corporate", "kids", "party-games", "card-game", "rentable", "rent-under-100","communication","social-deduction","social-interaction"] as GameTag[],
  },
  {
    slug: "7wonders",
    title: "7 Wonders",
    playerCount: "2-7",
    duration: "45 min",
    ageMin: 8,
    tags: ["corporate", "kids", "card-game", "engine-building","resource-management","rentable", "rent-under-100","card-drafting"] as GameTag[],
  },
  {
    slug: "skull",
    title: "Skull",
    playerCount: "3-6",
    duration: "20-40 min",
    ageMin: 8,
    tags: ["corporate", "kids", "party-games", "rentable", "rent-under-100","communication","social-deduction","social-interaction","bluffing", ] as GameTag[],
  },
  {
    slug: "zenith",
    title: "Zenith",
    playerCount: "2-4",
    duration: "30 min",
    ageMin: 8,
    tags: ["corporate", "kids", "card-game", "engine-building","resource-management","rentable", "rent-under-100","card-drafting"] as GameTag[],
  },
  {
    slug: "toy-battle",
    title: "Toy Battle",
    playerCount: "2",
    duration: "15 min",
    ageMin: 8,
    tags: ["corporate", "kids", "area-control", "1v1", "rentable", "rent-under-100"] as GameTag[],
  },
  {
    slug: "my-gold-mine",
    title: "My Gold Mine",
    playerCount: "2-6",
    duration: "25 min",
    ageMin: 7,
    tags: ["corporate", "kids", "resource-management", "push-your-luck", "rentable", "rent-under-100"] as GameTag[],
  },
  {
    slug: "welcome-to-the-dungeon",
    title: "Welcome to the Dungeon",
    playerCount: "2-4",
    duration: "20 min",
    ageMin: 8,
    tags: ["corporate", "kids", "card-game", "engine-building","resource-management","rentable", "rent-under-100","card-drafting"] as GameTag[],
  },
  {
    slug: "alias-party",
    title: "Alias Party",
    playerCount: "3-8",
    duration: "30 min",
    ageMin: 8,
    tags: ["corporate", "kids", "party-games", "rentable", "rent-under-100","communication","social-interaction"] as GameTag[],
  },
  {
    slug: "coup",
    title: "Coup",
    playerCount: "3-6",
    duration: "20 min",
    ageMin: 12,
    tags: ["corporate", "kids", "card-game", "social-deduction","social-interaction","rentable", "rent-under-100","card-drafting","bluffing"] as GameTag[],
  },
  {
    slug: "coatl",
    title: "Coatl",
    playerCount: "2-4",
    duration: "20 min",
    ageMin: 8,
    tags: ["corporate", "kids", "card-game", "engine-building","resource-management","rentable", "rent-under-100","card-drafting"] as GameTag[],
  },
  {
    slug: "one-night-ultimate-werewolf",
    title: "One Night Ultimate Werewolf",
    playerCount: "3-10",
    duration: "30 min",
    ageMin: 10,
    tags: ["corporate", "kids", "party-games", "rentable", "rent-under-100","communication","social-interaction","social-deduction","bluffing"] as GameTag[],
  },
  {
    slug: "marvel-united",
    title: "Marvel United",
    playerCount: "1-4",
    duration: "20-40 min",
    ageMin: 8,
    tags: ["corporate", "kids", "card-game", "cooperative","superheroes","rentable", "rent-under-100"] as GameTag[],
  },
  {
    slug: "activity",
    title: "Activity",
    playerCount: "3–16",
    duration: "45 min",
    ageMin: 10,
    tags: ["party-games", "word-games", "communication", "kids", "rentable", "rent-under-100"] as GameTag[],
  },
  {
    slug: "angel-fury",
    title: "Angel Fury",
    playerCount: "1–4",
    duration: "60–120 min",
    ageMin: 10,
    tags: ["strategy-games", "cooperative", "rentable", "rent-over-100"] as GameTag[],
  },
  {
    slug: "arkham-horror-tcg",
    title: "Arkham Horror: The Card Game",
    playerCount: "1–2",
    duration: "60–120 min",
    ageMin: 14,
    tags: ["card-game", "cooperative", "strategy-games", "venue-only"] as GameTag[],
  },
  {
    slug: "battlelore",
    title: "BattleLore",
    playerCount: "2",
    duration: "60 min",
    ageMin: 10,
    tags: ["strategy-games", "area-control", "1v1", "rentable", "rent-over-100"] as GameTag[],
  },
  {
    slug: "binding-of-isaac-four-souls",
    title: "The Binding of Isaac: Four Souls",
    playerCount: "2–4",
    duration: "30–60 min",
    ageMin: 12,
    tags: ["card-game", "strategy-games", "rentable", "rent-over-100"] as GameTag[],
  },
  {
    slug: "bloodborne-card-game",
    title: "Bloodborne: The Card Game",
    playerCount: "3–5",
    duration: "30–45 min",
    ageMin: 12,
    tags: ["card-game", "cooperative", "rentable", "rent-over-100"] as GameTag[],
  },
  {
    slug: "brew-crafters",
    title: "Brew Crafters",
    playerCount: "2–5",
    duration: "90 min",
    ageMin: 12,
    tags: ["strategy-games", "resource-management", "rentable", "rent-over-100"] as GameTag[],
  },
  {
    slug: "captain-marvel-secret-skrulls",
    title: "Captain Marvel: Secret Skrulls",
    playerCount: "4–7",
    duration: "30 min",
    ageMin: 10,
    tags: ["social-deduction", "card-game", "party-games", "rentable", "rent-under-100"] as GameTag[],
  },
  {
    slug: "century-big-box",
    title: "Century: Big Box",
    playerCount: "2–4",
    duration: "30–45 min",
    ageMin: 8,
    tags: ["strategy-games", "card-game", "resource-management", "rentable", "rent-over-100"] as GameTag[],
  },
  {
    slug: "chronicles-of-crime",
    title: "Chronicles of Crime",
    playerCount: "1–4",
    duration: "60–90 min",
    ageMin: 12,
    tags: ["cooperative", "logic-games", "rentable", "rent-over-100"] as GameTag[],
  },
  {
    slug: "citadels",
    title: "Citadels",
    playerCount: "2–8",
    duration: "20–60 min",
    ageMin: 10,
    tags: ["card-game", "social-deduction", "strategy-games", "rentable", "rent-under-100"] as GameTag[],
  },
  {
    slug: "codenames-duet",
    title: "Codenames: Duet",
    playerCount: "2",
    duration: "15–30 min",
    ageMin: 12,
    tags: ["corporate", "communication", "word-games", "cooperative", "rentable", "rent-under-100"] as GameTag[],
  },
  {
    slug: "concordia",
    title: "Concordia",
    playerCount: "2–5",
    duration: "90–100 min",
    ageMin: 12,
    tags: ["strategy-games", "resource-management", "venue-only"] as GameTag[],
  },
  {
    slug: "destinies",
    title: "Destinies",
    playerCount: "1–3",
    duration: "90–150 min",
    ageMin: 10,
    tags: ["cooperative", "strategy-games", "venue-only"] as GameTag[],
  },
  {
    slug: "disney-villainous",
    title: "Disney Villainous: The Worst Takes it All",
    playerCount: "2–6",
    duration: "45–120 min",
    ageMin: 10,
    tags: ["strategy-games", "family-games", "rentable", "rent-over-100"] as GameTag[],
  },
  {
    slug: "disney-villainous-wicked-to-the-core",
    title: "Disney Villainous: Wicked to the Core",
    playerCount: "2–3",
    duration: "40–60 min",
    ageMin: 10,
    tags: ["strategy-games", "family-games", "rentable", "rent-over-100"] as GameTag[],
  },
  {
    slug: "disney-villainous-evil-comes-prepared",
    title: "Disney Villainous: Evil Comes Prepared",
    playerCount: "2–3",
    duration: "40–60 min",
    ageMin: 10,
    tags: ["strategy-games", "family-games", "rentable", "rent-over-100"] as GameTag[],
  },
  {
    slug: "disney-villainous-perfectly-wretched",
    title: "Disney Villainous: Perfectly Wretched",
    playerCount: "2–3",
    duration: "40–60 min",
    ageMin: 10,
    tags: ["strategy-games", "family-games", "rentable", "rent-over-100"] as GameTag[],
  },
  {
    slug: "disney-villainous-despicable-plots",
    title: "Disney Villainous: Despicable Plots",
    playerCount: "2–3",
    duration: "40–60 min",
    ageMin: 10,
    tags: ["strategy-games", "family-games", "rentable", "rent-over-100"] as GameTag[],
  },
  {
    slug: "dungeon-mayhem",
    title: "Dungeon Mayhem",
    playerCount: "2–4",
    duration: "10 min",
    ageMin: 8,
    tags: ["card-game", "kids", "party-games", "rentable", "rent-under-100"] as GameTag[],
  },
  {
    slug: "dungeon-mayhem-monster-madness",
    title: "Dungeon Mayhem: Monster Madness",
    playerCount: "2–6",
    duration: "10 min",
    ageMin: 8,
    tags: ["card-game", "kids", "party-games", "rentable", "rent-under-100"] as GameTag[],
  },
  {
    slug: "elder-sign",
    title: "Elder Sign",
    playerCount: "1–8",
    duration: "90 min",
    ageMin: 12,
    tags: ["cooperative", "strategy-games", "rentable", "rent-over-100"] as GameTag[],
  },
  {
    slug: "everdell",
    title: "Everdell",
    playerCount: "1–4",
    duration: "40–80 min",
    ageMin: 10,
    tags: ["strategy-games", "engine-building", "resource-management", "rentable", "rent-over-100"] as GameTag[],
  },
  {
    slug: "gizmos",
    title: "Gizmos",
    playerCount: "2–4",
    duration: "40–50 min",
    ageMin: 8,
    tags: ["strategy-games", "engine-building", "kids", "rentable", "rent-over-100"] as GameTag[],
  },
  {
    slug: "gloom",
    title: "Gloom",
    playerCount: "2–5",
    duration: "60 min",
    ageMin: 10,
    tags: ["card-game", "strategy-games", "rentable", "rent-under-100"] as GameTag[],
  },
  {
    slug: "god-of-war-card-game",
    title: "God of War: The Card Game",
    playerCount: "1–4",
    duration: "90–180 min",
    ageMin: 10,
    tags: ["card-game", "cooperative", "strategy-games", "rentable", "rent-over-100"] as GameTag[],
  },
  {
    slug: "grimm-forest",
    title: "The Grimm Forest",
    playerCount: "2–4",
    duration: "45–60 min",
    ageMin: 8,
    tags: ["strategy-games", "kids", "family-games", "rentable", "rent-over-100"] as GameTag[],
  },
  {
    slug: "hansa-teutonica",
    title: "Hansa Teutonica: Big Box",
    playerCount: "3–5",
    duration: "45–90 min",
    ageMin: 12,
    tags: ["strategy-games", "area-control", "resource-management", "rentable", "rent-over-100"] as GameTag[],
  },
  {
    slug: "istanbul-big-box",
    title: "Istanbul: Big Box",
    playerCount: "2–5",
    duration: "40–90 min",
    ageMin: 10,
    tags: ["strategy-games", "resource-management", "rentable", "rent-over-100"] as GameTag[],
  },
  {
    slug: "legendary-marvel",
    title: "Legendary: A Marvel Deck Building Game",
    playerCount: "1–5",
    duration: "30–60 min",
    ageMin: 10,
    tags: ["card-game", "cooperative", "engine-building", "venue-only"] as GameTag[],
  },
  {
    slug: "mansions-of-madness",
    title: "Mansions of Madness: Second Edition",
    playerCount: "1–5",
    duration: "120–180 min",
    ageMin: 12,
    tags: ["cooperative", "strategy-games", "venue-only"] as GameTag[],
  },
  {
    slug: "marvel-champions",
    title: "Marvel Champions: The Card Game",
    playerCount: "1–4",
    duration: "45–90 min",
    ageMin: 12,
    tags: ["card-game", "cooperative", "engine-building", "venue-only"] as GameTag[],
  },
  {
    slug: "monopoly-cheaters",
    title: "Monopoly: Cheaters Edition",
    playerCount: "2–6",
    duration: "60–180 min",
    ageMin: 8,
    tags: ["family-games", "party-games", "kids", "rentable", "rent-over-100"] as GameTag[],
  },
  {
    slug: "munchkin",
    title: "Munchkin",
    playerCount: "3–6",
    duration: "60–120 min",
    ageMin: 10,
    tags: ["card-game", "party-games", "strategy-games", "rentable", "rent-over-100"] as GameTag[],
  },
  {
    slug: "paladins-west-kingdom",
    title: "Paladins of the West Kingdom",
    playerCount: "1–4",
    duration: "90–120 min",
    ageMin: 14,
    tags: ["strategy-games", "resource-management", "venue-only"] as GameTag[],
  },
  {
    slug: "pass-the-bomb",
    title: "Pass the Bomb: Party Edition",
    playerCount: "2–12",
    duration: "25 min",
    ageMin: 10,
    tags: ["party-games", "word-games", "communication", "rentable", "rent-under-100"] as GameTag[],
  },
  {
    slug: "prodigals-club",
    title: "The Prodigals Club",
    playerCount: "2–5",
    duration: "40–100 min",
    ageMin: 12,
    tags: ["strategy-games", "rentable", "rent-over-100"] as GameTag[],
  },
  {
    slug: "regatul-lui-enroh",
    title: "Regatul lui Enroh",
    playerCount: "2",
    duration: "60–150 min",
    ageMin: 12,
    tags: ["strategy-games", "1v1", "rentable", "rent-over-100"] as GameTag[],
  },
  {
    slug: "rise-of-queensdale",
    title: "The Rise of Queensdale",
    playerCount: "2–4",
    duration: "45–60 min",
    ageMin: 10,
    tags: ["strategy-games", "family-games", "rentable", "rent-over-100"] as GameTag[],
  },
  {
    slug: "root",
    title: "Root",
    playerCount: "2–4",
    duration: "60–90 min",
    ageMin: 14,
    tags: ["strategy-games", "area-control", "venue-only"] as GameTag[],
  },
  {
    slug: "slay-the-spire",
    title: "Slay the Spire: The Board Game",
    playerCount: "1–4",
    duration: "30–150 min",
    ageMin: 12,
    tags: ["card-game", "cooperative", "engine-building", "rentable", "rent-over-100"] as GameTag[],
  },
  {
    slug: "star-realms",
    title: "Star Realms",
    playerCount: "2",
    duration: "20 min",
    ageMin: 8,
    tags: ["card-game", "strategy-games", "1v1", "engine-building", "rentable", "rent-under-100"] as GameTag[],
  },
  {
    slug: "stone-age",
    title: "Stone Age",
    playerCount: "2–4",
    duration: "60–90 min",
    ageMin: 10,
    tags: ["strategy-games", "resource-management", "corporate", "rentable", "rent-over-100"] as GameTag[],
  },
  {
    slug: "stygian-society",
    title: "The Stygian Society",
    playerCount: "1–4",
    duration: "60–120 min",
    ageMin: 8,
    tags: ["cooperative", "strategy-games", "rentable", "rent-over-100"] as GameTag[],
  },
  {
    slug: "tekhenu",
    title: "Tekhenu: Obelisk of the Sun",
    playerCount: "1–4",
    duration: "60–120 min",
    ageMin: 14,
    tags: ["strategy-games", "resource-management", "venue-only"] as GameTag[],
  },
  {
    slug: "terraforming-mars",
    title: "Terraforming Mars",
    playerCount: "1–5",
    duration: "120 min",
    ageMin: 12,
    tags: ["strategy-games", "engine-building", "resource-management", "venue-only"] as GameTag[],
  },
  {
    slug: "thanos-rising",
    title: "Thanos Rising: Avengers Infinity War",
    playerCount: "2–4",
    duration: "60–90 min",
    ageMin: 8,
    tags: ["cooperative", "card-game", "kids", "rentable", "rent-over-100"] as GameTag[],
  },
  {
    slug: "this-war-of-mine",
    title: "This War of Mine: The Board Game",
    playerCount: "1–6",
    duration: "45–120 min",
    ageMin: 16,
    tags: ["cooperative", "strategy-games", "venue-only"] as GameTag[],
  },
  {
    slug: "unconscious-mind",
    title: "Unconscious Mind",
    playerCount: "1–4",
    duration: "60–120 min",
    ageMin: 14,
    tags: ["strategy-games", "resource-management", "venue-only"] as GameTag[],
  },
] as const;

export function getGames(locale: Locale): Game[] {
  const dict = getDictionary(locale);
  return GAME_BASE.map((game) => ({
    ...game,
    description:
      dict.games[game.slug]?.description ??
      "Board game experience by DiceZone.",
  }));
}

export function getRentalTerms(game: Pick<Game, "tags">): RentalTerms | undefined {
  if (!game.tags.includes("rentable")) return undefined;

  return game.tags.includes("rent-under-100")
    ? RENTAL_TERMS["under-100"]
    : RENTAL_TERMS["over-100"];
}

export function getGameBySlug(slug: string, locale: Locale): Game | undefined {
  return getGames(locale).find((g) => g.slug === slug);
}

export function getGamesByTag(tag: GameTag, locale: Locale): Game[] {
  return getGames(locale).filter((g) => g.tags.includes(tag));
}

export function getGameSlugs(): string[] {
  return GAME_BASE.map((g) => g.slug);
}

export function formatPrice(cents: number, locale: Locale): string {
  return new Intl.NumberFormat(locale === "ro" ? "ro-RO" : "en-US", {
    style: "currency",
    currency: locale === "ro" ? "RON" : "USD",
  }).format(cents / 100);
}
